### ISSUE TITLE
panic: interface conversion: opentracing.SpanContext is opentracing.noopSpanContext, not zipkintracer.SpanContext

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks-experiments/loki#3]
```
panic: interface conversion: opentracing.SpanContext is opentracing.noopSpanContext, not zipkintracer.SpanContext

goroutine 39 [running]:
panic(0x9f5160, 0xc4202451c0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/weaveworks/cortex/vendor/github.com/openzipkin/zipkin-go-opentracing.(*tracerImpl).startSpanWithOptions(0xc420241030, 0xa9ad4b, 0x14, 0xc42024b960, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/weaveworks/cortex/vendor/github.com/openzipkin/zipkin-go-opentracing/tracer.go:297 +0x5bb
github.com/weaveworks/cortex/vendor/github.com/openzipkin/zipkin-go-opentracing.(*tracerImpl).StartSpan(0xc420241030, 0xa9ad4b, 0x14, 0xc42024f060, 0x1, 0x1, 0x0, 0x1)
	/go/src/github.com/weaveworks/cortex/vendor/github.com/openzipkin/zipkin-go-opentracing/tracer.go:261 +0x102
github.com/weaveworks/cortex/vendor/github.com/opentracing/opentracing-go.startSpanFromContextWithTracer(0x7f2e6bc0a3e0, 0xc4201c98c0, 0xf90fc0, 0xc420241030, 0xa9ad4b, 0x14, 0xc42024f060, 0x1, 0x1, 0xc4201f7e30, ...)
	/go/src/github.com/weaveworks/cortex/vendor/github.com/opentracing/opentracing-go/gocontext.go:52 +0x14e
github.com/weaveworks/cortex/vendor/github.com/opentracing/opentracing-go.StartSpanFromContext(0x7f2e6bc0a3e0, 0xc4201c98c0, 0xa9ad4b, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/weaveworks/cortex/vendor/github.com/opentracing/opentracing-go/gocontext.go:44 +0x95
github.com/weaveworks/cortex/vendor/github.com/weaveworks/common/instrument.TimeRequestHistogramStatus(0x7f2e6bc0a3e0, 0xc4201c98c0, 0xa9ad4b, 0x14, 0xc420024580, 0xadf758, 0xc420045bf0, 0x1, 0x1)
	/go/src/github.com/weaveworks/cortex/vendor/github.com/weaveworks/common/instrument/instrument.go:41 +0x9b
github.com/weaveworks/cortex/vendor/github.com/weaveworks/common/instrument.TimeRequestHistogram(0x7f2e6bc0a3e0, 0xc4201c98c0, 0xa9ad4b, 0x14, 0xc420024580, 0xc420045bf0, 0x8, 0x80)
	/go/src/github.com/weaveworks/cortex/vendor/github.com/weaveworks/common/instrument/instrument.go:27 +0x70
github.com/weaveworks/cortex/chunk.(*DynamoTableManager).createTables(0xc4201c0460, 0x7f2e6bc0a3e0, 0xc4201c98c0, 0xc420187400, 0x5, 0x8, 0xc420187400, 0x5)
	/go/src/github.com/weaveworks/cortex/chunk/dynamo_table_manager.go:286 +0x733
github.com/weaveworks/cortex/chunk.(*DynamoTableManager).syncTables(0xc4201c0460, 0x7f2e6bc0a3e0, 0xc4201c98c0, 0x588ca665, 0x36c719a9)
	/go/src/github.com/weaveworks/cortex/chunk/dynamo_table_manager.go:131 +0x1ce
github.com/weaveworks/cortex/chunk.(*DynamoTableManager).loop.func1(0x7f2e6bc0a3e0, 0xc4201c98c0, 0xfab340, 0xc42014d1a0)
	/go/src/github.com/weaveworks/cortex/chunk/dynamo_table_manager.go:103 +0x3e
github.com/weaveworks/cortex/vendor/github.com/weaveworks/common/instrument.TimeRequestHistogramStatus(0x7f2e6bc0a3a0, 0xc420016268, 0xaa09f9, 0x1d, 0xc420024570, 0xadf758, 0xc420045ef8, 0xc420023e00, 0x7f2e6bc0a3a0)
	/go/src/github.com/weaveworks/cortex/vendor/github.com/weaveworks/common/instrument/instrument.go:45 +0x14d
github.com/weaveworks/cortex/vendor/github.com/weaveworks/common/instrument.TimeRequestHistogram(0x7f2e6bc0a3a0, 0xc420016268, 0xaa09f9, 0x1d, 0xc420024570, 0xc420045ef8, 0xc4201c4118, 0x1)
	/go/src/github.com/weaveworks/cortex/vendor/github.com/weaveworks/common/instrument/instrument.go:27 +0x70
github.com/weaveworks/cortex/chunk.(*DynamoTableManager).loop(0xc4201c0460)
	/go/src/github.com/weaveworks/cortex/chunk/dynamo_table_manager.go:104 +0x157
created by github.com/weaveworks/cortex/chunk.(*DynamoTableManager).Start
	/go/src/github.com/weaveworks/cortex/chunk/dynamo_table_manager.go:87 +0x5f
```

**Comment by tomwilkie** [comment]
This seems to happen if you create a span then change your default tracer.  I should probably stop using the zipkin data-structures...

**Comment by tomwilkie** [comment]
Moving the tracer initialisation into a `init()` function solved this.
